# Generated by Django 5.0.4 on 2024-05-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time_to_complete',
            field=models.IntegerField(default=120, verbose_name='время на выполнение'),
        ),
    ]
